logo:
    url: img/logo-square-120.png

post:
    cover: ball_1408.png
    img_dir: img/post/

layout:
    feature_count: 4

# busuanzi
busuanzi: false

# baidu push
baidu_push: true

# dict daily
## http://dict.cn/foot/help2.htm
dict_daily: false

# daily words
daily_words: true 

# Content
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# Code Highlight theme
# Available value:
#    normal | night | eighties | blue | bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

# Gitalk
# you can visit https://github.com/gitalk/gitalk for more details
gitalk:
  owner: o2team
  repo: o2team.github.io
  client_id: 3c4d153e6874260f9c7e
  client_secret: dd44012504c6168bc05b9266e0554bb28c62ce15

# Wechat
wechat:
  desc: "海海人生，无折腾不为乐。"
